In [3]:
import numpy as np

In [9]:
heights = np.array([160, 155, 172, 165, 180, 158, 175, 163, 171, 168])
heights

array([160, 155, 172, 165, 180, 158, 175, 163, 171, 168])

In [15]:
mean_height=np.mean(heights)
mean_height

166.7

In [17]:
median_height=np.median(heights)
median_height

166.5

In [19]:
std_height=np.std(heights)
std_height

7.5372408744845085

In [21]:
normal_heights=(heights-mean_height)/std_height
normal_heights

array([-0.88891945, -1.55229217,  0.70317509, -0.22554673,  1.76457144,
       -1.15426854,  1.10119872, -0.49089581,  0.57050054,  0.17247691])

In [25]:
print(np.mean(normal_heights))
print(np.std(normal_heights))

1.50712775592865e-15
0.9999999999999999


In [35]:
tallest=np.argmax(heights) #Tallest student
shortest=np.argmin(heights) #shortest student
print(f"Tallest: {tallest} and Shortest: {shortest}")

Tallest: 4 and Shortest: 1


In [33]:
print(heights[tallest])
print(heights[shortest])

180
155


In [29]:
tall_short_diff=np.max(heights)-np.min(heights)
print(f"Max height difference: {tall_short_diff}")

Max height difference: 25


In [41]:
heights_norep=np.random.choice(heights,5,replace=False) #Select random heights with no replacement
heights_norep

array([171, 155, 168, 175, 163])